# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.5/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hongkang/github/lake-head/computer-networks

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hongkang/github/lake-head/computer-networks

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hongkang/github/lake-head/computer-networks/CMakeFiles /Users/hongkang/github/lake-head/computer-networks//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hongkang/github/lake-head/computer-networks/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named computer_networks

# Build rule for target.
computer_networks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 computer_networks
.PHONY : computer_networks

# fast build rule for target.
computer_networks/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/build
.PHONY : computer_networks/fast

include/toml.o: include/toml.c.o
.PHONY : include/toml.o

# target to build an object file
include/toml.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/include/toml.c.o
.PHONY : include/toml.c.o

include/toml.i: include/toml.c.i
.PHONY : include/toml.i

# target to preprocess a source file
include/toml.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/include/toml.c.i
.PHONY : include/toml.c.i

include/toml.s: include/toml.c.s
.PHONY : include/toml.s

# target to generate assembly for a file
include/toml.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/include/toml.c.s
.PHONY : include/toml.c.s

include/tomlcpp.o: include/tomlcpp.cpp.o
.PHONY : include/tomlcpp.o

# target to build an object file
include/tomlcpp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/include/tomlcpp.cpp.o
.PHONY : include/tomlcpp.cpp.o

include/tomlcpp.i: include/tomlcpp.cpp.i
.PHONY : include/tomlcpp.i

# target to preprocess a source file
include/tomlcpp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/include/tomlcpp.cpp.i
.PHONY : include/tomlcpp.cpp.i

include/tomlcpp.s: include/tomlcpp.cpp.s
.PHONY : include/tomlcpp.s

# target to generate assembly for a file
include/tomlcpp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/include/tomlcpp.cpp.s
.PHONY : include/tomlcpp.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/main.cpp.s
.PHONY : main.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/queue.o: src/queue.cpp.o
.PHONY : src/queue.o

# target to build an object file
src/queue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/queue.cpp.o
.PHONY : src/queue.cpp.o

src/queue.i: src/queue.cpp.i
.PHONY : src/queue.i

# target to preprocess a source file
src/queue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/queue.cpp.i
.PHONY : src/queue.cpp.i

src/queue.s: src/queue.cpp.s
.PHONY : src/queue.s

# target to generate assembly for a file
src/queue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/queue.cpp.s
.PHONY : src/queue.cpp.s

src/source.o: src/source.cpp.o
.PHONY : src/source.o

# target to build an object file
src/source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/source.cpp.o
.PHONY : src/source.cpp.o

src/source.i: src/source.cpp.i
.PHONY : src/source.i

# target to preprocess a source file
src/source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/source.cpp.i
.PHONY : src/source.cpp.i

src/source.s: src/source.cpp.s
.PHONY : src/source.s

# target to generate assembly for a file
src/source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/source.cpp.s
.PHONY : src/source.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/computer_networks.dir/build.make CMakeFiles/computer_networks.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... computer_networks"
	@echo "... include/toml.o"
	@echo "... include/toml.i"
	@echo "... include/toml.s"
	@echo "... include/tomlcpp.o"
	@echo "... include/tomlcpp.i"
	@echo "... include/tomlcpp.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/queue.o"
	@echo "... src/queue.i"
	@echo "... src/queue.s"
	@echo "... src/source.o"
	@echo "... src/source.i"
	@echo "... src/source.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

