[source]

[[source.flows]]
type = "AUDIO"
streams = 2 # number of flows
mean_on_time = 0.36
mean_off_time = 0.64
peak_bit_rate = 64 # kbps
packet_size = 120
[[source.flows]]
type = "VIDEO"
streams = 1 # number of flows
mean_on_time = 0.33
mean_off_time = 0.73
peak_bit_rate = 384 # kbps
packet_size = 1000
[[source.flows]]
type = "DATA"
streams = 1 # number of flows
mean_on_time = 0.35
mean_off_time = 0.65
peak_bit_rate = 256 # kbps
packet_size = 583


[queue]

activate = "WFQ" # FIFO, SPQ, WFQ

[queue.FIFO]
size = 101 # K, maximum long long: 9223372036854775807

[queue.SPQ]
[[queue.SPQ.Q]] # AUDIO
size = 102
[[queue.SPQ.Q]] # VIDEO
size = 203
[[queue.SPQ.Q]] # DATA
size = 304

[queue.WFQ]
[[queue.WFQ.Q]] # AUDIO
weights = 0.5
size = 300
[[queue.WFQ.Q]] # VIDEO
weights = 0.3
size = 300
[[queue.WFQ.Q]] # DATA
weights = 0.2
size = 300

[server]
# transmission capacity of the system (kbits/s) (C)
rate = 255.227 # Î¼ for Little's formula
